config/routes.rb
Rails.application.routes.draw do
  get 'likes/toggle'
  devise_for :users
  resources :posts

	devise_scope :user do  
	get '/users/sign_out' => 'devise/sessions#destroy'
	end 

  get 'index/home', to: 'index#home'

  post 'comment/create', to: 'comments#create', as: :comments

  delete 'comments/:id', to: 'comments#destroy', as: :comments_delete

  post 'image/create', to: 'images#create', as: :images

  root 'index#home'

  post 'likes/toggle/:post_id', to: 'likes#toggle', as: :toggle_like


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user;
	belongs_to :post;
end

app/models/image.rb
class Image < ApplicationRecord
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
 validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
 	belongs_to :post
  
end

app/models/like.rb
class Like < ApplicationRecord

	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord

	belongs_to :user
	has_many :comments
	has_many :images
	has_many :likes

	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
 validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/


 	def user_can_like(user_id)

 		if self.likes.where(user_id: user_id).length>0

 			return false

 		else
 			return true

 		end

 	end


 	def user_like_string(user_id)

 		if self.user_can_like(user_id)

 			return '<i class="fas fa-thumbs-up"> </i> Like '.html_safe

 		else
 			return '<i class="fas fa-thumbs-up"></i> Like'.html_safe

 		end

 	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

         has_many :posts;
         has_many :comments;
         has_many :likes;

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	protect_from_forgery
	
	def after_sign_in_path_for(resource)
	  posts_path
	end
	def after_sign_out_path_for(resource)
	  posts_path
	end
	def after_sign_up_path_for(resource)
	  posts_path
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :authenticate_user!, only: [:create, :destroy]
	def create

		@comment = Comment.create(content: params[:comment][:content], post_id: params[:comment][:post_id], user_id: current_user.id);
		UserMailer.new_comment(@comment.id).deliver_now
		return redirect_to post_path(params[:comment][:post_id]);

	end

	def destroy
		abc = Comment.find(params[:id]);
		xyz = abc.post_id;
		abc.destroy;

		redirect_to post_path(xyz);

	end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

	def create
		
		image = Image.create(avatar: params[:image][:avatar], post_id: params[:image][:post_id]);
 		 return redirect_to post_path(params[:image][:post_id]);
 	end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def home
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  
  before_action :authenticate_user!
  def toggle
  
  	@post = Post.find(params[:post_id])

  	if @post.user_can_like(current_user.id)

  		@like = Like.create(user_id: current_user.id, post_id: params[:post_id]);

  	else
  		Like.find_by(user_id: current_user.id, post_id: params[:post_id]).destroy

  	end


  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json



  def index
    @posts = Post.paginate(:page => params[:page], :per_page => 9)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = Comment.all
    @image = Image.new
    @abc = Image.all
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    
    @post.user_id = current_user.id;

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content, :title, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/index/home.html.erb
<html>
<body id="home-body">


  <!-- Adding navbar here -->





  <!-- Adding jumbotron here -->

	<div class="container"> 
		<% if (notice) %>
			<div class="alert alert-primary alt" role="alert">
	 			 <p id="notice home-notice"><%= notice %></p>
			</div>
		<% end %>
		  	
	    	<div class="row">
	    		<div class="col-lg-12 col-md-12">
			      <div class="jumbotron jumb-image">
			      	<div class="small-screen-style">
			      	<div id = "content">
			        
				        <h1 id="size-road">Roadster</h1>
				        <h3>Where new journey begins</h3>
				        <button class="btn btn-default "><%= link_to 'Get started',posts_path, class: "link-style" %></button>
			     	</div>
			     </div>
			     </div>
			 </div>


	      </div>
  	</div>
    


  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roadster</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script|Great+Vibes|Merienda:400,700|Satisfy" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Kalam|Kaushan+Script" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=0.5">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/imagehover.css/1.0/css/imagehover.min.css">
     <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/noty/3.1.4/noty.css">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"></script>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
    
  <a class="navbar-brand" href="/">Roadster</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/posts">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>
      
      <li class="nav-item">
        <a class="nav-link" href="#">Contact</a>
      </li>
    </ul>


    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? == false %>
      <li class="nav-item">
        <a class="nav-link" href="../users/sign_in"><i class="fas fa-keyboard"></i>Sign-in</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="../users/sign_up">Sign-up</a>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
      </li>
      <% end %>

      
    </ul>
    
  </div>
</div>

</nav>
    <%= yield %>

    <script>
        new WOW().init();
    </script>
     <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/noty/3.1.4/noty.min.js"></script>
  </body>
</html>

app/views/likes/toggle.html.erb
<h1>Likes#toggle</h1>
<p>Find me in app/views/likes/toggle.html.erb</p>

app/views/likes/toggle.js.erb
console.log('like toggle called');
 var newLike = $('<%= escape_javascript render "posts/post_like_link", post: @post %>');
 // console.log('#post-<%= @post.id %>-likes');
// $('#post-<%= @post.id %>-likes').empty();
$('#post-<%= @post.id %>-likes').html(newLike);



new Noty({
    text: 'Like Status Changed!',
    theme: 'relax',
    type: 'success',
    layout: 'topRight',
     timeout: 1000
}).show();

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post_like_link.html.erb
<span class="like-font">
	<% if post.user_can_like(current_user.id) %>
			<%= link_to post.user_like_string(current_user.id), toggle_like_path(post), method: :post,remote: true, class: "btn btn-outline-info btn-sm out" %>  <%= post.likes.length%>
	 <% else %>
            <%= link_to post.user_like_string(current_user.id), toggle_like_path(post), method: :post,remote: true, class: "btn btn-success btn-sm color-button out" %>  <%= post.likes.length %>

          <% end %> 

</span>

app/views/posts/edit.html.erb
<html>

	<body id="new-body">

		<div class="container">

			<h1 class="h-new-style">New Post</h1>

		<%=form_for @post, html: { multipart: true } do |f| %>
			
			<div class="form-group">
			 	<%= f.label :title, class: "t-label-style"  %>
				<%= f.text_area :title, class: "form-control t-area-style" %>
				<br>
				<%= f.label :content, class: "c-label-style"%>
				<%= f.text_area :content, class: "form-control c-area-style" %>
			 	<br>
			 	<%= f.submit 'Submit', class: "btn btn-default sbt-new-style" %>
			 	
				<% end %>
			</div>

					
				<%= link_to 'Show', @post, class: "badge badge-success" %> |
				<%= link_to 'Back', posts_path, class: "badge badge-info" %>
		</div>
	</body>

</html>

app/views/posts/index.html.erb
<html>



<body id="post-background">
  

    <!-- Navbar added here by Layouts file -->

    <!-- Now adding Welcome page -->

  <header>
   
   <p id="notice"><%= notice %></p>
    <div class="container">

      <div class="jumbotron">

        <div class="content">

          <h1 class="welcome-style">Welcome to Roadster</h1>

          <h3>Start your journey </h3>

          <% if user_signed_in? %>
         <button class="btn btn-default"> <%= link_to 'Create Your Journey', new_post_path, class: "post-link-style" %></button>
          <% else %>
          <button class="btn btn-default"> <%= link_to "Sign in to create Journey", new_user_session_path, class: "post-link-style"%></button>
          <% end %> 
        </div>

        

      </div>
      

    </div>
  </header>


    <!-- Add new page that contains posts -->




  <main>
    <div class= "small-index-style">
      <div class="container">
        <div class="post-content">

        
            <div class="row">
                <div class="col-lg-12 "><h1 class="h-post-style">Journeys</h1></div>
              </div>
        
              <div class="row">
                <% @posts.each do |post| %>
                
                  <div class="grid-padding-style ">
                    <p class="paragh-style-1"><%=post.title %><p>
                      <p class="paragh-style-2">By -- <%= post.user.email %> </p>
                        <div id="test" class="col-lg-4 col-sm-6 col-xs-6 col-md-6"><%= image_tag post.avatar.url, class: "image-style wow fadeIn"%></div>

                    <br>
                    <div class="show-link">

                      <% if user_signed_in? %>
                          <div id="post-<%= post.id %>-likes">
                            <%= render 'post_like_link', post: post %>
                          </div>
                      <% else %>
                      <div class="like-a">
                        <a href = "users/sign_in"<button class='btn btn-outline-info btn-sm out'><i class="fas fa-thumbs-up"></i> Likes <%= post.likes.length %></button></a>
                      </div>

                      <% end %>

                  <%= link_to 'Show', post, class: 'edit-link btn btn-dark edit-link-show out'  %>
                    <% if user_signed_in? %>
                    <% if current_user.id == post.user_id %>
                    <% end %>
                    <% end %>
                    </div>
                  </div>
               
                  
                  
                    
                <% end %>
              </div>
                  

            <br>

            
            </div>
        </div>
      </div>
  <div class= "pag-style">
    <%= will_paginate @posts %>
  </div>

</main>
</footer>
</body>
</html>

app/views/posts/new.html.erb
<html>

	<body id="new-body">

		<div class="container">

			<h1 class="h-new-style">New Post</h1>

		<%=form_for @post, html: { multipart: true } do |f| %>
			
			<div class="form-group">
			 	<%= f.label :title, class: "t-label-style"  %>
				<%= f.text_area :title, class: "form-control t-area-style", required: true %>
				<br>
				<%= f.label :content, class: "c-label-style"%>
				<%= f.text_area :content, class: "form-control c-area-style", required: true %>
			 	<br>
			 	
			 	<p class="p-new-style">Choose Cover Image</p>
				<%= f.file_field :avatar, class: "form-control i-area-style", placeholder: "Enter email", required: true %>
				<br>
				
			 	<%= f.submit 'Submit', class: "btn btn-default sbt-new-style" %>
			 	
				<% end %>
			</div>

		<%= link_to 'Back', posts_path, class: "badge badge-info" %>
		</div>
	</body>

</html>

app/views/posts/show.html.erb
<html>
	<body id="show-body">
		<p id="notice"><%= notice %></p>

		<div class="container">

		  <div class="show-title-style">

		  	<%= @post.title%>
		  </div>
		 <div class="sml-content-style">
		  <div class="show-content-style">
		  	

		  	<%= @post.content %>
		  </div>
		</div>

		</div>

		<br>

	<% if user_signed_in? %>		
		<div class="container card-img-cmt">
			<div class=" card-image-style">
				<div class="card text-center">
					<div class="card-body">

							
							<%= form_for @image,html: { multipart: true }, remote:false do |f| %>
								<div class= "card-title">
					 				<%= f.label :image, class: "comment-paragh-style" %>
					 			</div>
									<%= f.file_field :avatar, required: true %>
					 				<%= f.hidden_field :post_id, value: @post.id%>
					 				<%= f.submit 'Submit', class: "btn btn-default sbt-new-style-i " %>
					 				<% end %>
				 		
	 				</div>
	 			</div>
	 		</div>

	 	
		 	<div class="comment-content">
		 		<div class="card text-center">
		 			<p class="comment-paragh-style"> Create Comments </p>

					<%= form_for @comment do |f| %>

						<div class= "card-title">
							<%= f.label :content, class: 'c-label-style' %>
							<%= f.text_field :content, class: 'form-control t-show-area-style', required: true %>
						</div>

						<%= f.hidden_field :post_id, value: @post.id %>
						<%= f.submit "Create", class: "btn btn-default sbt-new-style" %>
					<% end %>
				</div>
			</div>
		</div>
	<% else %>

		<div class="container card-img-cmt">
			<div class=" card-image-style">
				<div class="card text-center">
					<div class="card-body">
								<div class= "card-title comment-paragh-style">
					 				<p>Upload Image</p>
					 			</div>
									<p class="card-text c-label-style">In order to upload images you need to create your own post 
									and upload images on it</p>
				 		
	 				</div>
	 			</div>
	 		</div>

	 	
		 	<div class="comment-content">
		 		<div class="card text-center">
		 			<p class="comment-paragh-style"> Create Comments </p>

					<%= form_for @comment do |f| %>

						<div class= "card-title">
							<%= f.label :content, class: 'c-label-style' %>
							<%= f.text_field :content, class: 'form-control t-show-area-style' %>
						</div>

						<%= f.hidden_field :post_id, value: @post.id %>
						<%= f.submit "Create", class: "sbt-new-style" %>
					<% end %>
				</div>
			</div>
		</div>

	<% end %>
	











			<% u = Post.find(params[:id]) %>
			<% m = u.images.count %>

			<% c = u.comments.count %>
			<div class= "small-index-style">
				<div class="container img-show-cont">
					<div class="post-content">
						<div class="row">
            				<div class="col-lg-12 "><h1 class="h-post-style">Images</h1></div>
          				</div>
						
						<% if m==0 %>
							<div class="alert alert-primary" role="alert">
				 			 	<p>No images added</p>
							</div>
						<% end %>
							<div>	
								<div class="row">
									<% @post.images.each do |img| %>
				  						<div class="col-lg-4 col-md-6 col-sm-6"><%= image_tag img.avatar.url, class: "image-style-show wow fadeIn", target: '_blank'%></div>

				  					<% end %>
				  				</div>
				  			</div>
		  			</div>
		  		</div>
		  	</div>



						

			<div class="container">
				<p class="comment-paragh-style-1">Comments</p>
				<% if c==0 %>
						<div class="alt-comment">
							<div class="alert alert-primary" role="alert">
								
				 			 		<p>No Comments added</p>
				 			 </div>
						</div>
				<% end %>

				<% @post.comments.reverse.each do |comment| %>
	
						<div class="container bootstrap snippet">
						    <div class="row">
								<div class="col-md-12">
								    <div class="blog-comment"> 
										<ul class="comments">
										<li class="clearfix">
										  <div class="post-comments">
										      <p class="meta comment-paragh-style-2 "><%= comment.user.email %> says : </p>
										      <p class="show-content-style">
										          <%= comment.content %> <p class="cmt-delete">
										          	<% if user_signed_in? %>
												  	<% if current_user.id == @post.user_id %>
														<%= link_to "delete", comments_delete_path(comment), method: :delete %>
													<% end %>
													<% end %></p>
										      </p>
										  </div>
										</li>
										
										</ul>
									</div>
								</div>
							</div>
						</div>
				<% end %>
				
				<div>
					<%  post = @post %>
					<% if user_signed_in? %>
                         <div id="post-<%= post.id %>-likes">
                            <%= render 'post_like_link', post: post %>
                          </div>
                      <% else %>

                        <button class='btn btn-outline-info btn-sm' data-container="body" data-trigger="focus" data-toggle="popover" data-placement="bottom" data-content="Please sign-in to Like"><i class="fas fa-thumbs-up"></i> Likes <%= @post.likes.length %></button>

                      <% end %>

                  </div>











			</div>








































	

		<div class = "add-links-style">
				<% if user_signed_in? %>
				<% if current_user.id == @post.user_id %>
					<%= link_to 'Edit', edit_post_path(@post), class: "badge badge-success bdg-size" %> |
					<%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' },class: 'badge badge-danger bdg-size' %> |
				<% end %>
				<% end %>
			<%= link_to 'Back', posts_path, class: "badge badge-info bdg-size" %>
		</div>
	</body>
</html>